baseURL = "https://ifalm.github.io/"
languageCode = "en-us"
title = "My GIS Portfolio"
theme = ""

[params]
  author = "Inês Almiro"
  tagline = "GIS • Remote Sensing • Geospatial Analysis"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true